Patching Operator Mono produced the following errors due to attempting to remove missing glyphs:
Traceback (most recent call last):
  File "./powerline-fontpatcher", line 144, in <module>
    raise SystemExit(main(sys.argv[1:]))
  File "./powerline-fontpatcher", line 141, in main
    return patch_fonts(args.source_font, args.target_fonts, args.rename_font)
  File "./powerline-fontpatcher", line 133, in patch_fonts
    patch_one_font(source_font, target_font, rename_font)
  File "./powerline-fontpatcher", line 117, in patch_one_font
    target_font[0xFB01].removePosSub('*')  # fi ligature
TypeError: No such glyph

This commit first checks for the existence of glyphs 0xFB01 and 0xFB02 before attempting to remove them.